
project_id = "nkhgdoyzdlyixuaryfpa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[db.major_version]
version = 15

[studio]
enabled = true
port = 54323
immutable = false

[[inbuckets]]
id = "bucket1"
name = "bucket1"

[storage]
enabled = true

[functions]
enabled = true

[functions.bible-api]
verify_jwt = false

[functions.bible-import]
verify_jwt = false

[functions.bible-mysql]
verify_jwt = false
