// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkhgdoyzdlyixuaryfpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5raGdkb3l6ZGx5aXh1YXJ5ZnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODA2MzYsImV4cCI6MjA2MTM1NjYzNn0.B6GcY5V0EX6KwP4LnF63MPx6yW0BnNIoHrIJtOGaaMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);